```javascript
<div class="bg-gradient-to-r from-blue-500 to-purple-500 w-64 h-64">
  <!-- Content -->
</div>
```
This solution explicitly adds width and height to the div.  Ensure that no other conflicting CSS rules override the gradient. Check the order of your classes as well, making sure the gradient classes appear before any other classes that could potentially overwrite it. Also ensure that your Tailwind configuration is correctly setup and that the gradient classes are properly included in the CSS generated by the Tailwind build process.